######################################################################
# Automatically generated by qmake (3.0) Thu Aug 4 22:06:33 2016
######################################################################

TEMPLATE = app
TARGET = Tic-Tac-Toe
INCLUDEPATH += .
CONFIG += c++11
QT += widgets

# Input
HEADERS += applabel.h widget.h
SOURCES += applabel.cpp main.cpp widget.cpp
